"""create pecas table

Revision ID: 263c32d94c9a
Revises: 202605260002
Create Date: 2026-05-29 21:05:22.033345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '263c32d94c9a'
down_revision: Union[str, Sequence[str], None] = '202605260002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pecas_id'), 'pecas', ['id'], unique=False)
    op.create_index(op.f('ix_pecas_nome'), 'pecas', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pecas_nome'), table_name='pecas')
    op.drop_index(op.f('ix_pecas_id'), table_name='pecas')
    op.drop_table('pecas')
    # ### end Alembic commands ###