"""create ordem servico pecas table

Revision ID: 6c1787866707
Revises: fcba4f834866
Create Date: 2026-06-01 21:45:34.830529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1787866707'
down_revision: Union[str, Sequence[str], None] = 'fcba4f834866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordem_servico_pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordem_servico_pecas_id'), 'ordem_servico_pecas', ['id'], unique=False)
    op.create_index(op.f('ix_ordem_servico_pecas_ordem_servico_id'), 'ordem_servico_pecas', ['ordem_servico_id'], unique=False)
    op.create_index(op.f('ix_ordem_servico_pecas_peca_id'), 'ordem_servico_pecas', ['peca_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ordem_servico_pecas_peca_id'), table_name='ordem_servico_pecas')
    op.drop_index(op.f('ix_ordem_servico_pecas_ordem_servico_id'), table_name='ordem_servico_pecas')
    op.drop_index(op.f('ix_ordem_servico_pecas_id'), table_name='ordem_servico_pecas')
    op.drop_table('ordem_servico_pecas')
    # ### end Alembic commands ###